# -*- coding: utf-8 -*-
"""affine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yg8kQFuUq_ee2OYLFsdD3uUgnhSVRhif
"""

def encrypt(s, a, b):

	output = ''
  char=name

	for c in s:
		
		if ord(c) >= 0x41 and ord(c) <= 0x5a:
			i = ord(c) - 0x41
			i = ( i * a + b ) % 26
			output += chr(i + 0x41)

		elif ord(c) >= 0x61 and ord(c) <= 0x7a:
			i = ord(c) - 0x61
			i = ( i * a + b ) % 26
			output += chr(i + 0x61)

		else:
			output += c

	return output

if _name_ == "_main_":
	print( encrypt("Hello World!", 9, 13) )

def decrypt(s, a, b):

	output = ''

	a_inv = 0
	while a * a_inv % 26 != 1:
		a_inv += 1

	for c in s:
		
		if ord(c) >= 0x41 and ord(c) <= 0x5a:
			i = ord(c) - 0x41
			i = ( a_inv * (i-b) ) % 26
			output += chr(i + 0x41)

		elif ord(c) >= 0x61 and ord(c) <= 0x7a:
			i = ord(c) - 0x61
			i = ( a_inv * (i-b) ) % 26
			output += chr(i + 0x61)

		else:
			output += c

	return output

if _name_ == "_main_":
	print( decrypt("Yxiij Djkio!", 9, 13) )