# -*- coding: utf-8 -*-
"""ceaser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sr7KwXfZL7cmpJEu0UG29IQe7z-CvhbG
"""

def encryption(text,s):
    result = ""
    for i in range(len(text)):
        char = text[i]
        if (char.isupper()):
            result += chr((ord(char) + s-65) % 26 + 65)
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)
    return result
 
text = input("Enter the Plain text : ")
s = 3
print ("Plain Text : " + text)
enc=encryption(text,s)
print ("Cipher after Encryption: " + enc )

def decrypt(enc,s1):
    result = ""
    for i in range(len(enc)):
        char = enc[i]
        if (char.isupper()):
            result += chr((ord(char) + s1 - 65) % 26 + 65)
        else:
            result += chr((ord(char) + s1 - 97) % 26 + 97)
    return result
 
s1 = -3
dec=decrypt(enc,s1)
print ("Plane Text after decryption: " + dec )