# -*- coding: utf-8 -*-
"""dt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J-26LAHSruIo8W1L-D0MCQVQqYUyvjSu
"""

#imports needed libraries
import math

# Encryption method which takes in the message and the key
def encryptMessageWithoutKey(msg, size):
	
	#Blank string to store the encrypted text
	cipher = ""
	
	# track key indices
	k_indx = 0

	#Length of the key to find the size of the columns
	msg_len = float(len(msg))
	
	#converting the message into lists for handling 
	msg_lst = list(msg)
	
	#sorting the list of keys to identify the order of transposition
	key_lst = [item for item in range(0, size)]
	
    # calculate column of the matrix
	col = size

	# calculate maximum row of the matrix
	row = int(math.ceil(msg_len / col))

	# add the padding character '_' in the empty cell of the matrix
	fill_null = int((row * col) - msg_len)
	msg_lst.extend('_' * fill_null)

	# create Matrix and insert message and padding characters row-wise
	matrix = [msg_lst[i: i + col] for i in range(0, len(msg_lst), col)]

	# read matrix column-wise using key
	for _ in range(col):
		#current index
		curr_idx = key_lst.index(k_indx)
		#adding the required alphabet from the matrix into the string called cipher
		cipher += ''.join([row[curr_idx] for row in matrix])
		#incrementing the index
		k_indx += 1
		#end for

	#print(cipher)
	return cipher

def doubleTranspositionwithoutKey():
	#First transposition of the message
	stage_1 = encryptMessageWithoutKey(msg, size)

	#Displaying the intermediate stage
	print(f"\nSingle Transpotion Cipher of message '{msg}' with size '{size}':\t", stage_1)

	#Second transposition of the message i.e transposition of the cipher of stage 1
	cipher = encryptMessageWithoutKey(stage_1, size)

	#Printing the final cipher text
	print(f"\nDouble transposed message '{msg}' with size '{size}' is\t'",cipher,"'")


#reading input for the message
msg = input ("Enter the message to be encrypted: ")

#reading the column size from the user
size = int(input ("Enter the column: "))

#calling the driver function
doubleTranspositionwithoutKey()