# -*- coding: utf-8 -*-
"""rsa-a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRypPBcNLvBIvrevIk8gAu0FzFOb_ORf
"""

pip install rsa

import rsa


publicKey, privateKey = rsa.newkeys(512)


message = "hello geeks"

encMessage = rsa.encrypt(message.encode(),
            publicKey)

print("original string: ", message)
print("encrypted string: ", encMessage)


decMessage = rsa.decrypt(encMessage, privateKey).decode()

print("decrypted string: ", decMessage)