# -*- coding: utf-8 -*-
"""rsa-s.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxApztAa9OdzUpjaV7lzqx5RWEgJ3AM5
"""

pip install cryptography

from cryptography.fernet import Fernet

message = "hello geeks"



key = Fernet.generate_key()



fernet = Fernet(key)


encMessage = fernet.encrypt(message.encode())

print("original string: ", message)
print("encrypted string: ", encMessage)


decMessage = fernet.decrypt(encMessage).decode()

print("decrypted string: ", decMessage)